### ISSUE TITLE
Conditional branching and looping in R - Exercises - Annotation.ann

### ISSUE THREAD

**Issue by aylesse** [RockefellerUniversity/Intro_To_R_1Day#37]
Hi there,

Is this file type .ann a bug?  In the solution it also refers to it as  Annotation.txt ,and I wasn't sure how to open the .ann to see what it looks like before writing the code.  

Thanks!
Aylesse Sordillo

**Comment by matthew-paul-2006** [comment]
Yep. You're right. It was typo. Just fixing it now.
